[package]
name = "nom-cheatsheet"
version = "0.1.0"
authors = ["Rogier 'DocWilco' Mulhuijzen <github@bsdchicks.com>"]
edition = "2018"

[dependencies]
comrak = "0.15"
nom = "7.1"

[build-dependencies]
nom = "7.1"
itertools = "0.10"
