[package]
name = "nom-cheatsheet"
version = "0.1.0"
authors = ["Rogier 'DocWilco' Mulhuijzen <github@bsdchicks.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.35"
nom = "6.0.1"

[build-dependencies]
anyhow = "1.0.35"
itertools = "0.10.0"
nom = "6.0.1"
