[package]
name = "nom-cheatsheet"
version = "0.1.0"
authors = ["Rogier 'DocWilco' Mulhuijzen <github@bsdchicks.com>"]
edition = "2018"

[dependencies]
comrak = "0.29.0"
nom = "7.1.3"
syntect = "5.2.0"

[build-dependencies]
nom = "7.1.3"
itertools = "0.13.0"
